// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQt5Gc9oPSe__ZKVt5xemSjslk-rRwpTM',
    appId: '1:694289425649:web:fbe2d7d5fc1460d9b5b550',
    messagingSenderId: '694289425649',
    projectId: 'animal-health-1bd67',
    authDomain: 'animal-health-1bd67.firebaseapp.com',
    storageBucket: 'animal-health-1bd67.firebasestorage.app',
    measurementId: 'G-PT96K49Y0Y',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvN6YPr1d0HhkuuRCFXPC06VPl41ljsRs',
    appId: '1:694289425649:ios:f6f61aa6bb0f4b05b5b550',
    messagingSenderId: '694289425649',
    projectId: 'animal-health-1bd67',
    storageBucket: 'animal-health-1bd67.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationGg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQt5Gc9oPSe__ZKVt5xemSjslk-rRwpTM',
    appId: '1:694289425649:web:34e20fc33c53b76eb5b550',
    messagingSenderId: '694289425649',
    projectId: 'animal-health-1bd67',
    authDomain: 'animal-health-1bd67.firebaseapp.com',
    storageBucket: 'animal-health-1bd67.firebasestorage.app',
    measurementId: 'G-99CV5PCH95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAetiD-tS3DZi4vUh9Es8j2NKlRF4DZRXA',
    appId: '1:694289425649:android:e369cd28424f994eb5b550',
    messagingSenderId: '694289425649',
    projectId: 'animal-health-1bd67',
    storageBucket: 'animal-health-1bd67.firebasestorage.app',
  );
}
